### PR TITLE
GPT-3.5 prompt and response pairs for known cmd and bash commands

### PR DESCRIPTION
**Pull request by forrestmckee**
## Description

We add explanation and potential use cases for commands listed in `data/cmd_huge.known` and `data/bash_huge.known`

## Motivation and Context

While the collections of known commands are a value add, we propose further benefit in having a brief description of the commands.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA]([https://opensource.adobe.com/cla.html](https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Fopensource.adobe.com%2Fcla.html&data=05%7C01%7Cforrest.mckee%40peopletec.com%7C055cd8e88729494325bf08db25620e28%7C8a037cbdb8a04ef1a0b989e0443be2fd%7C0%7C0%7C638144875306902888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vnASb9Q1vSLHNuULqVvok%2BQemAwIf9Aip30hAsKaFN4%3D&reserved=0)).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tiberiu44** [comment]
Before being able to approve this PR, you need to sign the Adobe CLA (https://opensource.adobe.com/cla.html)

**Comment by forrestmckee** [comment]
> Before being able to approve this PR, you need to sign the Adobe CLA (https://opensource.adobe.com/cla.html)

Thanks for the swift reply. 
I sent an email to the address in the failed check. My colleague and I have signed the CLA already. Is there a way I can check on why that may not have been found?

**Comment by tiberiu44** [comment]
Hi @forrestmckee ,

If you signed the CLA after submitting this PR, I think you need to create a new one or try to re-run the tests. The only reason why signing the CLA will not work is if you used a different email address than the one you linked your github account with. 

Hope this help and thank you for the PR

**Comment by forrestmckee** [comment]
Thank you for your help, @tiberiu44 

I signed and submitted an updated copy with the email associated with my GitHub account. That seemed to allow for the checks to pass.

**Comment by tiberiu44** [comment]
Glad to hear it! I will look over the PR tomorrow.

**Review by tiberiu44 — APPROVED** [review]
This looks like good information and does not affect original functionality of the lol package. Thank you for the pull request.

**Pull request merged**
